// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnchorStatus } from "./AnchorStatus";

/**
 * 锚点解析结果；`found` 时 `heading` 为落点标题文本、`line` 为其 1-based 行号。
 */
export type AnchorInfo = { status: AnchorStatus, 
/**
 * found：落点标题文本；missing：请求的最后一段；none：null。
 */
heading: string | null, 
/**
 * found 时落点标题的 1-based 行号（前端滚动定位用），其余为 null。
 */
line: number | null, };
