// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorConfig } from "./EditorConfig";

/**
 * 生效配置（唯一类型定义点，TS 类型由 ts-rs 导出）。
 */
export type AppConfig = { version: number, 
/**
 * 上次打开的 vault 路径（mid-M1 "记住上次 vault" 消费；本波只定义不消费）。
 */
last_vault: string | null, editor: EditorConfig, };
