// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorConfig } from "./EditorConfig";
import type { HarnessConfig } from "./HarnessConfig";
import type { LogConfig } from "./LogConfig";
import type { UiConfig } from "./UiConfig";
import type { VaultConfig } from "./VaultConfig";

/**
 * 生效配置（唯一类型定义点，TS 类型由 ts-rs 导出）。
 */
export type AppConfig = { version: number, 
/**
 * 上次打开的 vault 路径（启动时 `restore_last_vault` 恢复，vault 打开成功时
 * `write_last_vault` 写回）。
 */
last_vault: string | null, editor: EditorConfig, 
/**
 * 界面主题（restyle-ui-tokens-v1）：`[ui]` 表，启动装载时施加一次。
 */
ui: UiConfig, 
/**
 * 键位覆盖表（M132）：键位写法 → 命令 id；值为 null 表示解绑该键位。
 * 键位写法与前端键位 token 同源（如 `"Cmd-s"`、`"Ctrl-Alt-Minus"`、`"ArrowUp"`）；
 * 多段 chord（含空白）本版不支持。命令 id 的合法性由前端键位层判定（见模块头）。
 */
keys: { [key in string]?: string | null }, 
/**
 * 运行时诊断日志（add-diagnostics-logging）：事件落盘等级。
 */
log: LogConfig, 
/**
 * vault 行为配置（change vault-open-ignore-set 的 r6）：`[vault]` 表。
 */
vault: VaultConfig, 
/**
 * 对话运行时配置（change add-harness-probe §11）：`[harness]` 表。消费方是 harness
 * 运行时（M302）：会话建立时读一次 provider 参数、权限规则表与循环上限。
 */
harness: HarnessConfig, };
