// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 反链条目：来源文件 + 行号 + 行级上下文（spec：反链面板只读派生视图）。
 */
export type BacklinkItem = { 
/**
 * 来源文件（vault 根相对路径）。
 */
source: string, 
/**
 * 链接所在行的 1-based 行号。
 */
line: number, 
/**
 * 链接所在行的原文（行级上下文）。
 */
context: string, };
