// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * command 错误信封（serde 序列化）。
 *
 * **职责分层（M282，change ui-language-i18n 的 D6 裁决）**：
 *   - `code` = 上屏文案的**键**：前端按它取文案表的条目（`src/copy.ts` 的 `errorText`），
 *     因此上屏文本随界面语言切换；
 *   - `params` = 那条文案要插的值（**按需携带**）：键名与文案表里的 `{占位名}` 同名；
 *   - `message` = **诊断日志的内容**与**未知 code 的兜底**（固定中文，不随界面语言变）——
 *     code 已知时 MUST NOT 直接上屏。
 */
export type CommandError = { 
/**
 * 机器可判定的稳定标识，snake_case。
 */
code: string, 
/**
 * 人话错误（中文）：日志内容与未知 code 的兜底，**不随界面语言变**。
 */
message: string, 
/**
 * 上屏文案的参数（键名 = `src/copy-data.ts` 里那条文案的 `{占位名}`）。
 * **空时不序列化**（`skip_serializing_if`），因此 TS 侧要按「可能缺席」读
 *（`src/copy.ts` 的 `ErrorEnvelope.params?` 就是这么声明的——ts-rs 的 `#[ts(optional)]`
 * 只接受 `Option<T>` 字段，这里不改类型，只在生成物上留一句注记）。
 */
params?: { [key in string]?: string }, };
