// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * command 错误信封（serde 序列化，前端可直接展示 `message`）。
 */
export type CommandError = { 
/**
 * 机器可判定的稳定标识，snake_case。
 */
code: string, 
/**
 * 人话错误（中文），前端可直接展示。
 */
message: string, };
