// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppConfig } from "./AppConfig";

/**
 * 一次配置加载的结果：生效配置 + 人话 warning 列表 + 实际读取路径。
 */
export type ConfigSnapshot = { config: AppConfig, 
/**
 * 逐字段回退时产生的人话提示；为空表示完全干净。
 */
warnings: Array<string>, path: string, };
