// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `wikilink_create` 成功 payload：新增文件的 vault 根相对路径。
 */
export type CreateNoteResult = { created: string, };
