// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorMode } from "./EditorMode";

export type EditorConfig = { 
/**
 * 编辑器模式（ADR 0002 §2 单内核双模式）。
 */
mode: EditorMode, };
