// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorMode } from "./EditorMode";

export type EditorConfig = { 
/**
 * 编辑器模式（ADR 0002 §2 单内核双模式）。
 */
mode: EditorMode, 
/**
 * md 模式的文件级折行（change line-wrap-options）：`true`（默认）时正文行在阅读栏内
 * 折行，`false` 时长行不折、由编辑区（`.cm-scroller`）横向平移呈现。只管 md 模式的正文
 * 行——围栏 / 缩进代码块行由 `code_block_wrap` 裁决（「一元素一条规则」），code 模式的
 * 正文行由 `code_mode_line_wrap` 裁决（M247 起两模式分叉，本键不再管 code 模式）。
 * TS 侧出厂默认同值，见 `src/preview/theme.ts` 的 `DEFAULT_LINE_WRAP`（两处写值各有
 * 单测钉住）。
 */
line_wrap: boolean, 
/**
 * 代码块折行：`false`（默认）时 md live preview 里的围栏 / 缩进代码块不折行、由块级
 * 横滚容器承载；`true` 时在阅读栏内折行（M138 以来的现状）。作用面只有 md 模式——
 * 非 md 文件没有围栏渲染，对它们无可观测效果（不是漏实现）。
 */
code_block_wrap: boolean, 
/**
 * code 模式正文行的折行（M247，change code-mode-line-wrap）：`false`（默认）时长行不折、
 * 由编辑区横向平移呈现，`true` 时在阅读栏内折行。
 *
 * **键缺席 = 出厂 `false`（即 code 模式不折行）**，与 md 模式的出厂 `line_wrap = true`
 * 构成「md 折 / code 不折」的出厂分叉（VS Code / JetBrains 同口径）；显式写 `true` 则听
 * 用户（把 code 模式也折起来）。本键**不跟随** `line_wrap`——跟随会让缺省值随全局取值
 * 漂移，出厂分叉随之失效。
 *
 * 作用面只有 code 模式：md 模式的正文行仍由 `line_wrap` 裁决，本键对 md 无可观测效果
 * （不是漏实现）。TS 侧出厂默认同值，见 `src/preview/theme.ts` 的
 * `DEFAULT_CODE_MODE_LINE_WRAP`（两处写值各有单测钉住）。
 */
code_mode_line_wrap: boolean, 
/**
 * `Enter` 换行的自动缩进（change enter-auto-indent）：`true`（默认）时 code 模式与 md 的
 * 围栏 / 缩进代码块内按 `Enter` 会按语法缩进（无缩进规则的语言沿用当前行行首空白）；
 * `false` 时这两处回到本 change 之前的行为（裸换行）。
 *
 * **键缺席 = 出厂 `true`**，且本键**不跟随**任何别的键（与 `code_mode_line_wrap` 同一条
 * 口径：缺省值只由本键自己的出厂值决定）。
 *
 * 作用面只有本 change 新增的两处：md 的列表项 / 引用续行是编辑器内核自带语言包的行为，
 * **本键对它无可观测效果**（`false` 时列表里按 Enter 仍会续写标记）——这是 D5a 的显式
 * 口径，不是漏实现。TS 侧出厂默认同值，见 `src/enter-indent.ts` 的 `DEFAULT_AUTO_INDENT`
 * （两处写值各有单测钉住）。
 */
auto_indent: boolean, 
/**
 * 正文（比例）字体族（change typography-and-zoom）：CSS `font-family` 值，`None` =
 * 沿用基线观感（`src/style.css` 的 `--font-sans`）。只在启动装载时读一次——本能力不做
 * 热重载，改字体需重启（字号另有运行期步进命令，不落盘）。
 *
 * 这里**只挡空串 / 纯空白**（→ `None` + warning）：值是否合法的 CSS 字族由前端判定
 *（`CSS.supports`），Rust 侧不复制一份 CSS 语法知识——与 `keys` 表「形状在此、语义在
 * 前端」的既有分层同口径（见模块头）。
 */
font_family: string | null, 
/**
 * 等宽字体族：口径同 `font_family`，缺省引用基线的 `--font-mono`。它同时是**列表标记
 * 宽度测量**与标记渲染共用的那个 token（`src/preview/lists.ts`），两处必须同源。
 */
mono_font_family: string | null, 
/**
 * 编辑器内容字号（px）：默认 15，合法区间 `[12, 32]`，区间外回落 15 + warning。
 * 它是编辑器内容面（md 正文 / 代码块 / code 模式）的字号；shell 的 13px 与阅读栏宽
 * 都不随之变（作用面由 token 分层结构性保证，见 change 的 design §2.2）。
 *
 * **这是本仓第一个数值配置字段**：写成字符串（`"font_size": "15"`）会在 serde 解析期
 * 失败 → 走**整文件回落**（全部字段回默认 + 一条 warning，连 `last_vault` 一起丢）。
 * 代价与「为什么不发明逐字段类型容忍」见模块头。
 */
font_size: number, };
