// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsChangeKind } from "./FsChangeKind";
import type { FsEntryKind } from "./FsEntryKind";

/**
 * 单条增量：变更类型 + 相对路径。
 */
export type FsChange = { kind: FsChangeKind, 
/**
 * 相对 vault 根的路径，`/` 分隔。
 */
path: string, 
/**
 * 条目类型（file/dir），deleted 时为 null——前端据此知道新增节点是文件还是目录。
 */
entry_kind: FsEntryKind | null, };
