// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsEntryKind } from "./FsEntryKind";

/**
 * 枚举条目：相对路径（`/` 分隔）、类型、大小、mtime（Unix 毫秒）。
 */
export type FsEntry = { 
/**
 * 相对 vault 根的路径，`/` 分隔。
 */
path: string, kind: FsEntryKind, 
/**
 * 字节数；目录为 0。
 */
size: number, 
/**
 * 修改时间（Unix 毫秒）；取不到时为 null。
 */
mtime_ms: number | null, };
