// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsChange } from "./FsChange";

/**
 * `fs:entry_changed` 事件 payload：debounce 窗口合并后的一批增量（同路径去重，后发生者胜）。
 */
export type FsEntryChangedEvent = { changes: Array<FsChange>, };
