// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单文件元数据（M218 doc-title/doc-meta 块的数据源）：mtime 取不到为 null，
 * 与 `FsEntry.mtime_ms` 同口径。
 */
export type FsFileMeta = { 
/**
 * 修改时间（Unix 毫秒）；取不到时为 null。
 */
mtime_ms: number | null, };
