// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarnessMockConfig } from "./HarnessMockConfig";
import type { HarnessProviderConfig } from "./HarnessProviderConfig";

/**
 * `[harness].providers` 表：三家 provider 各一段参数，**都保留**（切 provider 不丢配置）。
 */
export type HarnessProviders = { kimi: HarnessProviderConfig, deepseek: HarnessProviderConfig, 
/**
 * mock 是 fixture 驱动档，没有网络参数（验收专用）。
 */
mock: HarnessMockConfig, };
