// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * mock provider 的参数（验收专用，design §13）：脚本化响应的 fixture 文件路径。
 * `None` = 未配置（用 mock 档而未配 fixture 时由运行时给出人话错误）。
 */
export type HarnessMockConfig = { fixture: string | null, };
