// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarnessModelSpec } from "./HarnessModelSpec";

/**
 * 单个网络 provider 的参数。
 *
 * **`Default` 的 `model` 是空串，不是出厂模型名**：出厂模型名按 provider 分档
 * （[`DEFAULT_KIMI_MODEL`] / [`DEFAULT_DEEPSEEK_MODEL`]），由 [`HarnessProviders::default`]
 * 分派——这样「kimi 的默认 model」只有一处写值，两个 provider 不会互相串默认。
 * `api_key` 出厂为空串（未配置）、`base_url` 出厂为 `None`（官方地址）。
 */
export type HarnessProviderConfig = { 
/**
 * API key 明文（裁决点 2）。空串 = 未配置（出厂状态）——发送时由运行时给出人话错误。
 */
api_key: string, 
/**
 * 模型 id。空串 / 缺失时按 provider 回落出厂模型名（见 `Default` 的说明）。
 */
model: string, 
/**
 * API base URL；`None` = 用该 provider 的官方地址（官方值在运行时的预设表里，M302）。
 */
base_url: string | null, 
/**
 * 可选模型清单 + 每模型能力声明（M373）。**缺省 = 内置 preset**（kimi /
 * deepseek 各一份，见上）；用户显式声明（含空列表）则整体覆盖。这是浮层模型段
 * 与 ctx% 窗口 / effort 能力判定的共同数据源。
 */
models: Array<HarnessModelSpec>, };
