// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单个模型声明（M373，schema 暴露的 model 维度）：思考程度能力 + 上下文窗口。
 *
 * 这是**能力/窗口表的唯一真源**——thinking.rs 的 k3 词元判定与 llm.rs 的 KIMI_PRESET
 * 窗口表已退役为本结构的读取（内置 preset 见 [`KIMI_MODEL_PRESET`] /
 * [`DEEPSEEK_MODEL_PRESET`]，用户配置 `[harness].providers.<id>.models` 可整体覆盖）。
 */
export type HarnessModelSpec = { 
/**
 * 模型 id（配置值即读数，如 `kimi-k3` / `k3-256k`）。
 */
id: string, 
/**
 * 该模型是否支持思考程度调节（`reasoning.effort`）。未声明 / 未列出 = 不支持
 * （保守默认：不把无效参数发给不支持的模型）。
 */
effort: boolean, 
/**
 * 上下文窗口（tokens）：ctx% 读数的分母。
 */
window: bigint, };
