// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarnessPermissions } from "./HarnessPermissions";
import type { HarnessProvider } from "./HarnessProvider";
import type { HarnessProviders } from "./HarnessProviders";
import type { PermissionMode } from "./PermissionMode";

/**
 * `[harness]` 表（change add-harness-probe §11）：对话运行时的配置面。
 *
 * **生效时点**：会话建立 / 每轮请求时由 harness 运行时读一次（M302），不热重载——与
 * `editor` / `ui` 的「装载时施加」同路。`api_key` 明文（Alex 裁决点 2，理由见模块头）。
 */
export type HarnessConfig = { 
/**
 * 当前生效的 provider；其余两档的参数照旧保留在 `providers` 里（切回即恢复）。
 */
provider: HarnessProvider, 
/**
 * 三家 provider 各自的参数表：`provider` 键切换生效项。
 */
providers: HarnessProviders, 
/**
 * 权限规则表（design §6）：deny > allow > 默认分层（读 allow / 写与 CLI ask）。
 */
permissions: HarnessPermissions, 
/**
 * 权限模式（change add-harness-permission-modes，design §2/§7）：`read_only` /
 * `vault_write`（默认）/ `full_access`。切换对下一个判定生效，不打断进行中的轮次。
 */
permission_mode: PermissionMode, 
/**
 * 工具循环上限（默认 50，合法区间见 [`LOOP_MAX_MIN`] / [`LOOP_MAX_MAX`]）。
 */
loop_max: number, 
/**
 * 上下文用量警示阈值（百分比，默认 85，合法区间见 [`WARN_CTX_PCT_MIN`] / [`WARN_CTX_PCT_MAX`]）。
 */
warn_ctx_pct: number, 
/**
 * 自动压缩（默认 true）：一轮响应完成后 ctx% 越阈值即自动压缩续聊；false 退化为纯手动。
 */
auto_compact: boolean, };
