// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 对话 provider 三档（change add-harness-probe §11）：`kimi` / `deepseek` 均 OpenAI 兼容契约，
 * `mock` 是验收专用的 fixture 驱动档（真机验收不依赖真实外部 API）。**闭集合**：取值校验在
 * Rust 侧完成，运行时拿到的必是三档之一（与 `UiTheme` / `EditorMode` / `LogLevel` 同一形态）。
 */
export type HarnessProvider = "kimi" | "deepseek" | "mock";
