// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarnessModelSpec } from "./HarnessModelSpec";

/**
 * 单个网络 provider 的参数。
 *
 * M381 起（config-only）`Default` 的 `model` 是空串、`models` 是空清单：**不内置任何
 * 出厂模型**——模型清单、当前 model、逐模型能力/窗口一律只来自 config.json 的
 * `[harness].providers.<id>` 声明（`model` 缺省/空时由 validate 解析为声明清单首项 id，
 * 清单为空则保持空串，发送时由运行时给出人话错误）。`api_key` 出厂为空串（未配置）、
 * `base_url` 出厂为 `None`（官方地址）。
 */
export type HarnessProviderConfig = { 
/**
 * API key 明文（裁决点 2）。空串 = 未配置（出厂状态）——发送时由运行时给出人话错误。
 */
api_key: string, 
/**
 * 模型 id（配置值即读数）。缺省 / 空串 → 声明清单首项 id；清单为空 → 空串（不伪造）。
 */
model: string, 
/**
 * API base URL；`None` = 用该 provider 的官方地址（官方值在运行时的预设表里，M302）。
 */
base_url: string | null, 
/**
 * 可选模型清单 + 每模型能力声明（M373；M381 起 config-only）：**唯一真源是配置
 * 声明**——不写 `models` 键 = 空清单（provider 节已配置时给一条人话 warning +
 * 前端提示态），绝不回落内置表。这是浮层模型段与 ctx% 窗口 / effort 能力判定的
 * 共同数据源。
 */
models: Array<HarnessModelSpec>, };
