// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 解析三态 + 不支持（spec §3 与 §6）。
 */
export type LinkStatus = "resolved" | "ambiguous" | "unresolved" | "unsupported";
