// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnchorInfo } from "./AnchorInfo";
import type { EmbedTarget } from "./EmbedTarget";
import type { LinkStatus } from "./LinkStatus";

/**
 * `link_graph_resolve` 的解析结果 payload。
 */
export type LinkResolveResult = { status: LinkStatus, 
/**
 * resolved / ambiguous（chosen）的目标路径，vault 根相对；其余为 null。
 */
path: string | null, 
/**
 * ambiguous 时的全部候选（字典序）；其余为空数组。
 */
candidates: Array<string>, 
/**
 * 仅 embed 形态且解析到文件时有值（spec §5）。
 */
embed_target: EmbedTarget | null, anchor: AnchorInfo, };
