// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

/**
 * 诊断日志配置（`[log]` 表）。
 */
export type LogConfig = { level: LogLevel, };
