// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 日志等级：`info` = 记录 v0 事件集全部事件；`off` = 事件丢弃不写盘。
 * 两档来自裁决点 1（默认 info：dogfood 期需要数据）。
 */
export type LogLevel = "info" | "off";
