// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * md 模式行号 gutter 的在场档位（change goto-line-command 的 D4 二次改判，2026-09-28）。
 * 它不切换任何 token，只决定 `lineNumbers()` 在 md 模式何时在场：
 * `on-demand` = 默认档，md 文档打开时无行号，跳转输入条（`⌥G`）在场时显示、收起后隐藏；
 * `always` = md 常驻显示行号；
 * `off` = md 恒不显示行号。
 * **闭集合**：取值校验在 Rust 侧完成，前端拿到的必是这三档之一，不再判非法（与 `UiTheme`
 * / `EditorMode` / `LogLevel` 同一形态）。**只管 md**：code 模式的行号恒常显，不读本键。
 */
export type MarkdownLineNumbers = "on-demand" | "always" | "off";
