// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 面板消息（`harness_state` 快照 `messages[]` 的元素；m303 宽容解析，缺字段=空态）。
 */
export type PanelMessage = { 
/**
 * user / assistant / tool / compact。
 */
role: string, 
/**
 * 完整文本（user/assistant 的主内容）。
 * **空时不序列化**（`skip_serializing_if`）——TS 侧按「可能缺席」读。
 */
text?: string, 
/**
 * 恢复重建的思考展示文本（M398）：仅当 wire 的 reasoning 回放项里取得到**明文**时带值
 * （kimi 的 `encrypted_content` 项取不到 → 缺省，不伪造）。活会话的思考块由
 * `reasoning_chunk` 事件驱动、不进面板记录——本字段只在恢复重建的面板消息上有值。
 */
reasoning?: string, 
/**
 * 摘要（compact 消息的压缩摘要，面板可展开）。
 */
summary?: string, 
/**
 * 工具名（tool 消息）。
 */
name?: string, 
/**
 * 执行状态：tool 消息的工具终态（done / denied / rejected / error）；
 * assistant 消息的中断标注（"stopped" = 本轮被用户停止，面板 D383 徽标的数据源，M348）。
 */
status?: string, 
/**
 * 消息入会话的时刻（UNIX 秒）；面板据它显示相对时间（缺该字段的旧快照退化为不显示）。
 */
ts: number, };
