// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个 pane 的会话：有序的相对路径 + 激活项。
 */
export type PaneSession = { 
/**
 * 有序的 vault 相对路径（固定标签；预览标签不入盘）。
 */
tabs: Array<string>, 
/**
 * 激活项（vault 相对路径）；非法值落为 null（前端按「退化到第一个可打开的标签」处理）。
 */
active: string | null, };
