// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReadingPositionEntry } from "./ReadingPositionEntry";

/**
 * 一个 vault 的阅读位置表（version + 键为 vault 相对路径的条目）。
 */
export type ReadingPositions = { version: number, entries: { [key in string]?: ReadingPositionEntry }, };
