// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一份文档的阅读位置（唯一类型定义点，TS 类型由 ts-rs 导出）。
 *
 * 三个量的语义**由前端定义**（本模块不参与换算）：`pos` 是文档位置锚（视口顶附近的行块起始
 * 位置），`y` / `x` 是该锚的字符盒相对滚动容器顶 / 左的实际偏移。`at` 只用于容量淘汰，不参与
 * 恢复判定。
 */
export type ReadingPositionEntry = { pos: number, y: number, x: number, 
/**
 * 写入时刻（Unix 毫秒）：写入侧填，读取侧只用于淘汰排序。
 */
at: number, };
