// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `harness_resume_session` 的返回（ts-rs 导出；前端恢复 UI mission 的消费形状）：
 * 从留存文件恢复出来的会话**续写的新会话**——新 session id 是新 JSONL 留存的文件名，
 * 前端据此知道「当前会话接在了哪份留存上」，面板重渲染走 `harness_state`。
 */
export type SessionResumeInfo = { 
/**
 * 续写的新会话 id（`sessions/<id>.jsonl` 的文件名）。
 */
session_id: string, 
/**
 * 灌回的 LLM 侧历史条数（`input` 项数）：源文件最后一条会话轮次 llm_request 的
 * messages，加末尾未入请求的 llm_response 折叠项（design §6.2 第 4 步——reasoning
 * 回放项 + assistant 消息 + 悬空的 function_call 项）；空会话恢复为 0。
 */
restored_items: number, };
