// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PanelMessage } from "./PanelMessage";

/**
 * `harness_resume_session` 的返回（ts-rs 导出；前端恢复 UI mission 的消费形状）：
 * 从留存文件恢复出来的会话**续写的新会话**——新 session id 是新 JSONL 留存的文件名，
 * 前端据此知道「当前会话接在了哪份留存上」，面板重渲染走 `harness_state`。
 */
export type SessionResumeInfo = { 
/**
 * 续写的新会话 id（`sessions/<vault 稳定 id>/<id>.jsonl` 的文件名）。
 */
session_id: string, 
/**
 * 灌回的 LLM 侧历史条数（`input` 项数）：源文件最后一条会话轮次 llm_request 的
 * messages，加末尾未入请求的 llm_response 折叠项（design §6.2 第 4 步——reasoning
 * 回放项 + assistant 消息 + 悬空的 function_call 项）；空会话恢复为 0。
 */
restored_items: number, 
/**
 * 面板重建用的渲染消息（M398，design §6.2「面板（transcript）从灌回的 input 重建」）：
 * 把灌回的 input 项按序映射成面板视角的 user / assistant / tool 消息（reasoning 明文
 * 挂在紧随其后的 assistant 消息上），新会话的 `panel` 与之一致（同一份重建结果的副本，
 * 快照恢复与本次返回因此不会漂）。前端据此一次重放、不必再拉 `harness_state`。
 */
messages: Array<PanelMessage>, };
