// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `harness_list_sessions` 的元素（ts-rs 导出；前端会话选择器的消费形状）：
 * 一份本 vault 留存会话的摘要。
 */
export type SessionSummary = { 
/**
 * 留存文件名去 `.jsonl`（`sessions/<vault 稳定 id>/<session_id>.jsonl`）；也是恢复命令的入参。
 */
session_id: string, 
/**
 * 文件内第一条 `llm_request` 的首条 user 消息的**原始提问段**——自动注入的
 * 「当前编辑器上下文」节已由后端剥除（`turn.rs` 的 `strip_context_section`；注入形态的
 * 单一真源在那里）；未截断——会话名「约 20 字」的截断规则在前端。该会话还没有用户消息时为 None。
 */
first_user_text?: string, 
/**
 * 首行 `session_open` 信封的 UNIX 秒（会话建立时刻）；缺 ts 的历史文件为 None。
 */
ts?: number, };
