// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 思考程度三档（Alex 2026-10-06 裁决：Low / High / Max，默认 High）。
 *
 * **闭集合**：取值校验在 Rust 侧完成，前端拿到的必是三档之一（与 `UiTheme` / `HarnessProvider`
 * 同一形态）。档位名作为专有名词，zh/en 两档界面均保持英文原文，故序列化为小写英文原词。
 */
export type ThinkingEffort = "low" | "high" | "max";
