// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThinkingEffort } from "./ThinkingEffort";

/**
 * 思考程度在快照里的读出面（面板思考 chip 的数据源，M362）。
 *
 * 键集合与序列化同在 `harness_state` 的 `thinking` 字段里：`level` = 当前档位（会话内生效，
 * 新会话回到默认 High），`supported` = 当前 provider + model 是否支持程度调节
 *（false ⇒ 前端置灰禁用 + hover 说明，Alex 2026-10-06 裁决点 2）。
 */
export type ThinkingState = { level: ThinkingEffort, supported: boolean, };
