// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadFile } from "./ThreadFile";
import type { ThreadStatus } from "./ThreadStatus";

export type Thread = { id: string, title: string, status: ThreadStatus, files: Array<ThreadFile>, recent_activity: string, brief: string | null, };
