// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarkdownLineNumbers } from "./MarkdownLineNumbers";
import type { UiLanguage } from "./UiLanguage";
import type { UiTheme } from "./UiTheme";

/**
 * 界面配置（`[ui]` 表，restyle-ui-tokens-v1）。与 `EditorConfig` 同为结构化表：
 * 逐字段取值校验，缺字段回落默认、取值非法回落默认 + warning。
 */
export type UiConfig = { 
/**
 * 界面主题，默认 `light`。**启动真源**：启动装载时读一次并施加到
 * `documentElement.dataset.theme`（首帧主题）；运行期由 `view.theme-cycle`（⌘⇧T）与
 * modeline 主题钮循环三档，**切换即经 `config_set_ui_value` 回写本字段**，让真源跟上运行态
 *（M237，change live-theme-switch；与 `editor.font_size` 的「运行期 MUST NOT 回写」不同
 * ——主题是设备 / 场景级的持久偏好）。取值由 `UiTheme` 闭集合校验；不跟随系统主题。
 */
theme: UiTheme, 
/**
 * 阅读栏宽上限（框宽 px，content-width-drag，M228）：默认 760（D1，2026-09-26 Alex 修订），
 * 合法区间 `[760, 1200]`（D2——默认值即下限）。启动时装配一次；运行期由栏宽拖拽推进并回写
 *（`config_set_ui_value`，与 `editor.font_size` 的「运行期 MUST NOT 回写」不同——
 * 宽度是用户显式调整的**持久偏好**，回写即本能力的核心语义）。
 * 类型不符（`"content_width": "760"`）与 `font_size` 同路：serde 解析期失败 →
 * 整文件回落。
 */
content_width: number, 
/**
 * md 模式行号 gutter 的在场档位（change goto-line-command 的 D4 二次改判，2026-09-28），
 * 默认 `on-demand`。**只管 md**：只读 code 模式的行号 gutter 恒常显、不读本键。
 * 与 `editor.mode` / `editor.font_size` 同路：**装载时读一次、运行期 MUST NOT 回写**
 *（本 change 不提供切换它的命令 / 键位 / UI，因此没有 live 切换的触发源——与 `theme`
 * 的差别正在这里，`theme` 有 modeline 主题钮那个落点）。
 */
markdown_line_numbers: MarkdownLineNumbers, 
/**
 * 界面语言（change ui-language-i18n，M282）：默认 **`en`**（Alex 2026-09-27 节点 1 裁决
 * 「我希望产品的默认语言是英文」）。**启动真源**：启动装载时读一次并由前端
 * `applyLanguage` 施加到 `documentElement.lang`；运行期由 `view.language-cycle`（⌘⇧L）与
 * modeline 语言钮切换，**切换即经 `config_set_ui_value` 回写本字段**（与 `theme` 同路）。
 * 取值由 `UiLanguage` 闭集合校验；**只管界面文案**——文档内容、文件名、日志与配置告警
 * 都 MUST NOT 随它变。
 */
language: UiLanguage, };
