// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiTheme } from "./UiTheme";

/**
 * 界面配置（`[ui]` 表，restyle-ui-tokens-v1）。与 `EditorConfig` 同为结构化表：
 * 逐字段取值校验，缺字段回落默认、取值非法回落默认 + warning。
 */
export type UiConfig = { 
/**
 * 界面主题，默认 `light`。启动装载时读一次并施加到 `documentElement.dataset.theme`
 * ——与 `editor.mode` 同口径（重启生效）。本版不做运行期切换、不跟随系统主题。
 */
theme: UiTheme, };
