// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 界面语言（change ui-language-i18n，M282）：**闭集合**两档，取值校验在 Rust 侧完成，
 * 前端拿到的必是这两档之一，不再判非法（与 `UiTheme` / `EditorMode` / `LogLevel` 同一形态）。
 * 默认 `en`（Alex 2026-09-27 节点 1 裁决）。它**只管界面文案的取值列**：文档内容、文件名、
 * 日志与配置告警不随它变（日志面固定语言，见 change 的 Non-goals）。
 */
export type UiLanguage = "en" | "zh";
