// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneSession } from "./PaneSession";

/**
 * 一个 vault 的 pane 布局会话（唯一类型定义点，TS 类型由 ts-rs 导出）。
 *
 * **`harness_pane` 是 ADR 0008 Decision 6 登记的 Phase 2 契约位**：Phase 1 恒 `false`，
 * 只随 schema 落盘、**无消费者**（读取侧也不解释它，见 `SessionFile`）。Phase 2 harness
 * 归位 pane 后，消费点在装配层的布局恢复一带（`src/main.ts` 的 `applyPaneCount`）——
 * 届时它决定 harness pane 的落位。此处与 design §10 的标注同源，防「声明了却没有消费者」
 * 误判；不给它造一个假的 Phase 1 消费者。
 */
export type VaultSession = { version: number, 
/**
 * 各 pane 的会话，按横向顺序。空数组由 [`sanitize`] 补成「单空 pane」，读取侧因此恒有
 * 至少一个 pane（前端据此区分「单 pane」与「分栏」）。
 */
panes: Array<PaneSession>, harness_pane: boolean, 
/**
 * 分隔条位置（`SPLIT_RATIO_MIN..=SPLIT_RATIO_MAX`；越界 / 非有限值由 [`sanitize`] 钳制）。
 */
pane_split_ratio: number, 
/**
 * 落盘时间（Unix 毫秒）：写入侧填，读取侧不参与判断。
 */
updated_at: number, };
