// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[vault]` 表（change vault-open-ignore-set 的 r6，Alex 裁决第 7 条）：决定**用户规则**
 * 从哪些文件读——内置规则（`fs_io::BUILTIN_NAMES` 那 16 个名字 + 临时文件模式）恒定生效、
 * **不在**配置面内，也不可被用户规则的取反推翻（§2.6）。
 *
 * **唯一消费者**：`commands::prepare_vault_open` 构造 `fs_io::IgnorePolicy` 时的那一步
 *（把清单里的 vault 相对路径逐个读成 gitignore 规则）——本字段没有第二个读点，`config_get`
 * 只是把它原样交给前端展示（REVIEW.md 第 9 条：配置项声明即被消费）。因此它的生效时点是
 * **vault 装载时**（每次装载现场读一次配置，MUST NOT 用启动期缓存钉住），改动下次装载生效。
 */
export type VaultConfig = { 
/**
 * 用户规则的来源清单：每个值是**vault 相对路径**，一律按「vault 根的规则文件」解释
 *（模式相对 vault 根匹配，MUST NOT 被当成「相对该文件所在目录」的规则）。
 *
 * - **空列表 = 没有用户规则来源**：只剩内置规则（= 非 git vault 的等价行为）。这是
 *   彻底的——列表里不含 `.gitignore` 时，递归途中的嵌套 `.gitignore` 同样不读（嵌套
 *   逐层读取是「`.gitignore` 这个来源」的固有语义，不是第二个配置面）。
 * - 文件不存在 / 不是常规文件 ⇒ 静默跳过（`.git/info/exclude` 在非 git vault 里本来就
 *   不存在，这是常态而不是异常）。
 * - 非法项（非字符串 / 绝对路径 / 含 `..` / 空串）逐项忽略并各给一条人话 warning，
 *   其余项照常生效——MUST NOT 因为一项非法而把整份配置（含别的字段）回退默认值。
 */
rule_files: Array<string>, };
