// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VaultInfo } from "./VaultInfo";

/**
 * 前端启动时查询的 vault 状态。
 */
export type VaultStatus = { 
/**
 * 当前打开的 vault；未打开为 null。
 */
vault: VaultInfo | null, 
/**
 * 人话提示（如 last_vault 恢复失败）；无提示为 null。前端可直接展示。
 */
notice: string | null, };
