// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个 vault 的标签会话（唯一类型定义点，TS 类型由 ts-rs 导出）。
 */
export type VaultSession = { version: number, 
/**
 * 有序的 vault 相对路径（固定标签；预览标签不入盘，design §4.2）。
 */
tabs: Array<string>, 
/**
 * 激活项（vault 相对路径）；非法值落为 null（前端按「退化到第一个可打开的标签」处理）。
 */
active: string | null, 
/**
 * 落盘时间（Unix 毫秒）：写入侧填，读取侧不参与判断。
 */
updated_at: number, };
