// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 列表行（`vault_list` 的契约形状）：注册表摘要 + 路径可用性 + 可恢复的标签数。
 * 显示名取路径的目录名（MUST NOT 引入独立显示名或命名步骤）；`tab_count` 与会话里
 * 「将被恢复的固定标签数」同源（预览标签不入盘，design §4.2）。
 */
export type VaultListEntry = { id: string, path: string, 
/**
 * 显示名 = 路径的目录名（basename）。
 */
name: string, 
/**
 * 路径当前可用（目录存在）。不可用项保留在列表里、不可切换，只给「重新定位…」。
 */
available: boolean, 
/**
 * 上次打开成功时间（Unix 毫秒）；无记录为 null。
 */
last_opened_at: number | null, 
/**
 * 可恢复的固定标签数（会话文件里的合法条目数）；无历史为 0。
 */
tab_count: number, };
