// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsEntry } from "./FsEntry";

/**
 * 已打开 vault 的快照：根路径 + 全量枚举结果。
 */
export type VaultInfo = { 
/**
 * vault 根目录绝对路径。
 */
root: string, entries: Array<FsEntry>, };
