// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 剪贴板图片落盘结果（`fs_write_attachment` 的返回值，ts-rs 导出给前端）。
 */
export type WrittenAttachment = { 
/**
 * 最终 vault 相对路径（去重命中时为既有文件所在位置——首贴位置赢）。
 */
path: string, 
/**
 * 内容寻址文件名 `pasted-<hash16>.<ext>`——前端据此拼 `![[name]]` 引用，不自己拼名字。
 */
name: string, };
