import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdir, writeFile, readFile } from "node:fs/promises";
import path from "node:path";
const prepare = () => execFileSync(process.execPath, ["scripts/visual/prepare-isolated.mjs"], { encoding: "utf8" }).trim();
const snapshot = (run, stage) => JSON.parse(execFileSync(process.execPath, ["scripts/visual/snapshot-isolated.mjs", run, stage], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }));
test("unique runs do not inherit Thread/current/workspace; evidence redacts and fails closed", async () => {
  const old = prepare();
  await mkdir(path.join(old, "config/lumir/threads"));
  await writeFile(path.join(old, "config/lumir/threads/current-old.txt"), "old");
  const run = prepare();
  assert.notEqual(old, run);
  assert.deepEqual(snapshot(run, "before-create").current, []);
  await mkdir(path.join(run, "config/lumir/threads"));
  await mkdir(path.join(run, "config/lumir/workspaces"));
  await writeFile(path.join(run, "config/lumir/threads/test.json"), JSON.stringify({ id: "test", vault_id: "test-vault", title: "private title", status: "active", files: [] }));
  await writeFile(path.join(run, "config/lumir/workspaces/test.json"), JSON.stringify({ id: "test-vault", path: path.join(run, "vault") }));
  const after = snapshot(run, "after-create");
  assert.equal(after.threads[0].title, "<redacted>");
  assert.equal(after.workspaces[0].path, "<run>/vault");
  const restart = snapshot(run, "after-restart");
  assert.deepEqual(restart.threads, after.threads);
  assert.deepEqual(restart.current, []);
  assert.throws(() => snapshot(run, "after-restart"));
  assert.throws(() => snapshot(path.dirname(run), "before-create"));
  const bad = prepare();
  await mkdir(path.join(bad, "config/lumir/threads"));
  await writeFile(path.join(bad, "config/lumir/threads/bad.json"), "{");
  assert.throws(() => snapshot(bad, "before-create"));
  assert.equal(await readFile(path.join(old, "config/lumir/threads/current-old.txt"), "utf8"), "old");
});
